# Build settings
markdown: redcarpet
#highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "J. Justin Wilson"
description: > # this means to ignore newlines until "email:"
  Director of Communications @ij & @Scouts4Equality

email: j@jamesjwilson.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/green.jpg"

name: 'J. Justin Wilson'
author: 'J. Justin Wilson'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "http://jjust.in" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jjustinwilson'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jjustinwilson
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
    url:	https://facebook.com/jjustinwilson
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jjustinwilson
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
